import { expect, test } from 'playwright/test';
import { guideSections } from '@/lib/guide/content';

function section(id: string) {
  const found = guideSections.find((s) => s.id === id);
  expect(found, `guide section "${id}" exists`).toBeTruthy();
  return found!;
}

test.describe('Guide — Connecting WordPress', () => {
  test('section sits right before WordPress Publishing', () => {
    const ids = guideSections.map((s) => s.id);
    expect(ids.indexOf('wordpress-connection')).toBe(ids.indexOf('wordpress-publish') - 1);
    expect(new Set(ids).size).toBe(ids.length);
  });

  test('explains where and how to create the Application Password', () => {
    const text = section('wordpress-connection').points.join('\n');
    expect(text).toContain('Users → Profile → Application Passwords');
    expect(text).toMatch(/dedicated to OmniFlow/);
    expect(text).toMatch(/WP Username field must contain the real username/);
    expect(text).toMatch(/usually the administrator account/);
    expect(text).toMatch(/Application Password field must contain the Application Password generated by WordPress/);
    expect(text).toMatch(/only a label/);
    expect(text).toMatch(/it is not the username/);
    expect(text).toMatch(/Never use your normal login password/);
    expect(text).toMatch(/Never share your Application Password/);
    expect(text).toMatch(/main HTTPS address/);
    expect(text).toContain('without /wp-admin');
  });

  test('has the troubleshooting notes', () => {
    const text = section('wordpress-connection').points.join('\n');
    expect(text).toContain('username/Application Password combination rejected');
    expect(text).toMatch(/not the name you gave the Application Password/);
    expect(text).toContain('curl.exe');
    expect(text).toContain('Invoke-WebRequest');
  });

  test('never shows a real-looking Application Password', () => {
    const text = section('wordpress-connection').points.join('\n');
    // WordPress Application Passwords are 24 chars shown as six groups of four.
    expect(text).not.toMatch(/\b[A-Za-z0-9]{4}( [A-Za-z0-9]{4}){5}\b/);
    expect(text).not.toMatch(/Basic [A-Za-z0-9+/=]{8,}/);
  });

  test('WordPress Publishing points to the connection section', () => {
    expect(section('wordpress-publish').points[0]).toContain('"Connecting WordPress"');
  });
});
