import type { NicheProfile, NicheSections } from './types';

// Niche profiles (Phase 1: code only, not customizable per project — that is
// Phase 2, migration 041). Priority niches: Crochet, Clay, Home Decor,
// Recipes. `label` is the value the niche suggestions store in
// projects.niche (components/projects/project-form.tsx), so existing projects
// resolve without any data change. Add a future niche by adding one entry to
// NICHE_PROFILES — no prompt or route change is needed.

const COMMON_ANTI_INVENTION = [
  'Never invent measurements, quantities, timings, prices, brand names, product specifications or results that the source does not give.',
  'Never claim that something is easy, quick, cheap, beginner-friendly, safe or guaranteed unless the keyword or the source explicitly says so.',
];

/** Fallback for a free-text or unknown niche — and the base of every profile's missing fields. */
export const GENERIC_NICHE_SECTIONS: NicheSections = {
  shared: {
    audience: 'Readers interested in the topic of the keyword and the project niche.',
    positioning: 'Useful, trustworthy content that answers what the reader is actually looking for.',
    tone: ['clear', 'helpful', 'natural'],
    expertiseLevel: 'Adapt to the keyword: explain the basics without talking down to experienced readers.',
    recommendedVocabulary: [],
    avoidVocabulary: ['hype words ("ultimate", "insane", "game-changer")', 'vague adjectives ("beautiful", "amazing", "stunning") without a concrete detail'],
    priorityTopics: [],
    antiInventionRules: COMMON_ANTI_INVENTION,
  },
  wordpress: {
    searchIntents: ['informational', 'how-to', 'inspiration'],
    articleStructures: ['Follow the article type and structure already requested in these instructions.'],
    seoRules: ['Use the vocabulary the niche audience actually searches with, in the article language.'],
    detailLevel: 'Concrete and practical: every section gives the reader something they can use.',
    faqRules: ['Questions a real reader of this niche would search for, never generic "what is X" filler.'],
    linkRules: ['Internal links are added automatically by the server after generation — never write internal links.', 'External links: only the URLs explicitly provided in these instructions.'],
    cta: 'A low-pressure invitation to keep reading or save the article.',
  },
  pinterest: {
    angles: ['Use the five structured angles already defined in these instructions.'],
    titleRules: ['Natural, specific titles in the pin language; the keyword topic stays recognizable.'],
    descriptionRules: ['Useful, specific descriptions that make the reader want to open the pin.'],
    keywordRules: ['Search terms this audience types on Pinterest, in the pin language, never unrelated trending terms.'],
    saveStrategy: 'Make each pin worth saving on its own: one clear idea, one clear benefit.',
    diversityRules: ['Vary the idea, the promise and the scene of every pin — never synonym swaps.'],
    boards: [],
    overlayRules: ['Short, readable hooks only when this project uses on-image text.'],
    cta: 'Invite the reader to save the pin or discover more.',
  },
  visual: {
    style: 'Realistic, well-composed photography that shows the topic clearly.',
    framing: 'Choose the framing that shows the subject best.',
    lighting: 'Natural, soft light.',
    materials: [],
    colors: [],
    props: [],
    textInImage: 'No text, lettering, logo or watermark inside the image itself.',
  },
};

export const NICHE_PROFILES: NicheProfile[] = [
  {
    slug: 'crochet',
    label: 'Crochet',
    aliases: ['Crocheting', 'Crochet Patterns', 'Crochet & Knitting', 'Amigurumi'],
    shared: {
      audience: 'Crocheters of every level looking for projects, patterns and technique help.',
      positioning: 'Cozy, practical crochet inspiration with patterns and techniques people can actually make.',
      tone: ['warm', 'cozy', 'encouraging', 'practical'],
      expertiseLevel: 'Mixed: explain stitch names and terms the first time, never assume advanced skills unless the keyword does.',
      recommendedVocabulary: ['stitch', 'yarn weight', 'hook size', 'pattern', 'gauge', 'amigurumi', 'granny square', 'rows', 'rounds'],
      avoidVocabulary: ['knitting terms used as crochet terms', 'invented stitch names'],
      priorityTopics: ['crochet patterns', 'amigurumi', 'granny squares', 'blankets', 'wearables', 'stitch tutorials', 'yarn choice'],
      antiInventionRules: [
        ...COMMON_ANTI_INVENTION,
        'Never invent a stitch count, yarn yardage, hook size or finished dimension that the source does not give.',
        'Do not mix US and UK crochet terms; when the source does not say which, use US terms consistently.',
      ],
    },
    wordpress: {
      searchIntents: ['free pattern / how to make', 'stitch tutorial', 'project ideas', 'yarn and tool choice'],
      articleStructures: ['Materials → steps → finishing for a single project', 'Idea list with the skill and materials each needs'],
      seoRules: ['Use the exact project or stitch name readers search for (e.g. "granny square", "amigurumi").'],
      detailLevel: 'Step-level: name stitches and materials precisely, but never invent pattern numbers.',
      faqRules: ['Questions about yarn, hook size, stitch substitutions, sizing and care.'],
      linkRules: GENERIC_NICHE_SECTIONS.wordpress.linkRules,
      cta: 'Invite the reader to save the pattern or try the project.',
    },
    pinterest: {
      angles: ['finished project reveal', 'pattern or stitch discovery', 'cozy idea list', 'problem-solution for a common crochet struggle'],
      titleRules: ['Name the project or stitch; keep it cozy and specific, never clickbait.'],
      descriptionRules: ['Mention what the piece is and what the reader will learn or make, without giving the full pattern.'],
      keywordRules: ['Combine the project type with "crochet" and a style or use (e.g. "crochet blanket pattern").'],
      saveStrategy: 'Pins people save for their next project: one clear make per pin.',
      diversityRules: ['Vary the project, the yarn colors and the setting between pins.'],
      boards: ['Crochet Patterns', 'Amigurumi', 'Crochet Blankets', 'Crochet Ideas'],
      overlayRules: ['A short hook naming the project, readable over soft backgrounds.'],
      cta: 'Save this pattern for your next project.',
    },
    visual: {
      style: 'Close-up craft photography of a finished crochet piece.',
      framing: 'Overhead or 45-degree, the piece front and center.',
      lighting: 'Soft, warm, cozy natural light.',
      materials: ['yarn', 'cotton', 'wool', 'wood'],
      colors: ['soft neutrals', 'warm pastels'],
      props: ['yarn skeins', 'a crochet hook', 'a wooden surface or knit blanket'],
      textInImage: GENERIC_NICHE_SECTIONS.visual.textInImage,
    },
    subNiches: [
      { slug: 'amigurumi', label: 'Amigurumi', aliases: ['Crochet Toys', 'Crochet Animals'], shared: { priorityTopics: ['amigurumi patterns', 'stuffed crochet toys', 'safety eyes and stuffing'] } },
      { slug: 'crochet-blankets', label: 'Crochet Blankets', aliases: ['Blankets', 'Granny Squares'], shared: { priorityTopics: ['blanket patterns', 'granny squares', 'joining methods'] } },
      { slug: 'crochet-wearables', label: 'Crochet Wearables', aliases: ['Crochet Clothes', 'Crochet Tops', 'Crochet Accessories'], shared: { priorityTopics: ['tops', 'hats', 'bags', 'sizing and drape'] } },
    ],
  },
  {
    slug: 'clay-crafts-diy',
    label: 'Clay Crafts & DIY',
    aliases: ['Clay', 'Clay Crafts', 'Clay Crafts and DIY', 'Clay DIY', 'clay-crafts-diy', 'Air Dry Clay', 'Polymer Clay'],
    shared: {
      audience: 'Makers who want beautiful, useful clay projects at home, including people trying clay for the first time.',
      positioning: 'Beautiful + Easy + Useful: approachable clay projects that look good and serve a purpose.',
      tone: ['friendly', 'creative', 'practical', 'beginner-friendly voice'],
      expertiseLevel: 'Approachable: explain each step plainly, without assuming prior clay experience.',
      recommendedVocabulary: ['air dry clay', 'polymer clay', 'bake', 'cure', 'sand', 'seal', 'glaze', 'handmade'],
      avoidVocabulary: ['kiln-fired pottery terms for air-dry or polymer projects', 'Crochet or knitting vocabulary'],
      priorityTopics: [
        'Air Dry Clay', 'Polymer Clay', 'Clay Projects', 'Clay Home Decor', 'Learn Clay', 'Seasonal Clay',
        'Useful Clay Projects', 'Clay Magnets', 'Cute Clay Ideas', 'Clay Charms', 'Clay Tutorials',
      ],
      antiInventionRules: [
        ...COMMON_ANTI_INVENTION,
        'Never invent drying times, baking temperatures, curing times or brand-specific instructions that the source does not give; say to follow the clay manufacturer’s instructions instead.',
        'Never claim a clay piece is food-safe, waterproof or child-safe unless the source says so.',
      ],
    },
    wordpress: {
      searchIntents: ['how to make', 'project ideas', 'clay type choice', 'finishing and sealing'],
      articleStructures: ['Materials → shaping → drying or baking → finishing for a single project', 'Idea list grouped by use or season'],
      seoRules: ['Name the clay type (air dry or polymer) and the object readers search for (e.g. "clay magnets", "clay trinket dish").'],
      detailLevel: 'Practical steps with the tools and materials named; timings only when the source gives them.',
      faqRules: ['Questions about clay type, drying or baking, sealing, painting and durability.'],
      linkRules: GENERIC_NICHE_SECTIONS.wordpress.linkRules,
      cta: 'Invite the reader to save the project or try it with their own colors.',
    },
    pinterest: {
      angles: ['finished piece reveal', 'useful object you can make', 'seasonal clay idea', 'cute idea list', 'learn a clay technique'],
      titleRules: ['Name the object and the clay type when known; friendly, specific, never clickbait.'],
      descriptionRules: ['Say what the piece is and why it is useful or pretty, without claiming it is easy unless the source says so.'],
      keywordRules: ['Combine the object with the clay type or "clay" (e.g. "air dry clay dish", "polymer clay charms").'],
      saveStrategy: 'Pins people save as their next make: one clear object per pin.',
      diversityRules: ['Vary the object, the colors and the surface between pins; never the same piece twice.'],
      boards: ['Air Dry Clay Ideas', 'Polymer Clay Projects', 'Clay Home Decor', 'Clay Charms'],
      overlayRules: ['Optional; when used, a short hook naming the object.'],
      cta: 'Optional — when used, invite the reader to save the idea.',
    },
    visual: {
      style: 'Modern Handmade: finished clay pieces clearly visible as the main subject.',
      framing: 'Overhead or 45-degree.',
      lighting: 'Soft natural daylight.',
      materials: ['air dry or polymer clay', 'matte or glazed surfaces', 'light wood', 'linen', 'plaster'],
      colors: ['soft or earthy tones: terracotta, sand, sage, cream, blush'],
      props: ['a few clay tools', 'a simple styled surface', 'a small plant or dried flowers at most'],
      textInImage: GENERIC_NICHE_SECTIONS.visual.textInImage,
    },
    subNiches: [
      { slug: 'air-dry-clay', label: 'Air Dry Clay', aliases: ['Air-Dry Clay', 'Air Dry'], shared: { priorityTopics: ['air dry clay projects', 'drying and cracking', 'sealing air dry clay'] } },
      { slug: 'polymer-clay', label: 'Polymer Clay', aliases: ['Polymer'], shared: { priorityTopics: ['polymer clay projects', 'baking polymer clay', 'polymer clay earrings'] } },
      { slug: 'clay-home-decor', label: 'Clay Home Decor', aliases: ['Clay Decor'], shared: { priorityTopics: ['trinket dishes', 'vases', 'candle holders', 'wall decor'] } },
      { slug: 'seasonal-clay', label: 'Seasonal Clay', aliases: ['Christmas Clay', 'Holiday Clay'], shared: { priorityTopics: ['seasonal ornaments', 'holiday decor', 'gift ideas'] } },
      { slug: 'clay-magnets', label: 'Clay Magnets', aliases: ['Magnets'], shared: { priorityTopics: ['clay magnets', 'fridge magnets'] } },
      { slug: 'clay-charms', label: 'Clay Charms', aliases: ['Charms', 'Clay Jewelry', 'Clay Earrings'], shared: { priorityTopics: ['clay charms', 'clay earrings', 'keychains'] } },
      { slug: 'cute-clay-ideas', label: 'Cute Clay Ideas', aliases: ['Cute Clay'], shared: { priorityTopics: ['cute clay figures', 'small gifts'] } },
      { slug: 'useful-clay-projects', label: 'Useful Clay Projects', aliases: ['Useful Clay'], shared: { priorityTopics: ['organizers', 'dishes', 'holders'] } },
      { slug: 'learn-clay', label: 'Learn Clay', aliases: ['Clay Tutorials', 'Clay Basics'], shared: { priorityTopics: ['clay basics', 'tools', 'techniques'] } },
    ],
  },
  {
    slug: 'home-decor',
    label: 'Home Organization & Decor',
    aliases: ['Home Decor', 'Home Décor', 'Home Organization', 'Home Organisation', 'Interior Design', 'Decor'],
    shared: {
      audience: 'People styling, organizing or refreshing their home.',
      positioning: 'Realistic, livable home ideas — style and organization that work in real rooms.',
      tone: ['inspiring', 'practical', 'calm'],
      expertiseLevel: 'General audience: explain design terms briefly when used.',
      recommendedVocabulary: ['layout', 'storage', 'styling', 'texture', 'palette', 'small space', 'makeover'],
      avoidVocabulary: ['brand or product names not in the source', 'renovation costs not in the source'],
      priorityTopics: ['room ideas', 'small-space storage', 'styling', 'seasonal decor', 'organization systems'],
      antiInventionRules: [
        ...COMMON_ANTI_INVENTION,
        'Never invent product dimensions, prices, store names or renovation costs.',
      ],
    },
    wordpress: {
      searchIntents: ['room ideas / inspiration', 'how to organize', 'styling tips', 'small-space solutions'],
      articleStructures: ['Ideas grouped by room or by problem', 'Step-by-step organization or makeover plan'],
      seoRules: ['Name the room and the goal readers search for (e.g. "small bathroom storage").'],
      detailLevel: 'Actionable ideas that describe placement, materials and why each works.',
      faqRules: ['Questions about small spaces, renters, budget-friendly options and maintenance — without inventing prices.'],
      linkRules: GENERIC_NICHE_SECTIONS.wordpress.linkRules,
      cta: 'Invite the reader to save the ideas for their own space.',
    },
    pinterest: {
      angles: ['room transformation', 'storage problem-solution', 'style idea list', 'fresh look discovery'],
      titleRules: ['Name the room or space and the benefit.'],
      descriptionRules: ['Describe the idea and the feeling of the space without revealing every tip.'],
      keywordRules: ['Room + style or goal (e.g. "boho living room ideas", "small closet organization").'],
      saveStrategy: 'Pins people save for their own room: one clear idea per pin.',
      diversityRules: ['Vary the room, the style and the palette between pins.'],
      boards: ['Home Decor Ideas', 'Home Organization', 'Small Space Living'],
      overlayRules: ['Only when this project uses on-image text.'],
      cta: 'Save this idea for your next refresh.',
    },
    visual: {
      style: 'Full-room interior photography of a real, livable space.',
      framing: 'The whole space in context — never an isolated close-up object.',
      lighting: 'Natural daylight.',
      materials: ['wood', 'linen', 'ceramic', 'rattan'],
      colors: ['a coherent 2-3 color palette per room'],
      props: ['furniture and decor that belong in that room'],
      textInImage: GENERIC_NICHE_SECTIONS.visual.textInImage,
    },
    subNiches: [
      { slug: 'home-organization', label: 'Home Organization', aliases: ['Organization', 'Storage'], shared: { priorityTopics: ['storage systems', 'decluttering', 'small-space organization'] } },
      { slug: 'seasonal-decor', label: 'Seasonal Decor', aliases: ['Christmas Decor', 'Fall Decor', 'Holiday Decor'], shared: { priorityTopics: ['seasonal decor', 'holiday styling'] } },
    ],
  },
  {
    slug: 'recipes',
    label: 'Food & Recipes',
    aliases: ['Recipes', 'Recipe', 'Food', 'Cooking', 'Food and Recipes', 'Baking'],
    shared: {
      audience: 'Home cooks looking for recipes they can make and enjoy.',
      positioning: 'Reliable, appetizing home recipes with clear ingredients and steps.',
      tone: ['warm', 'appetizing', 'clear'],
      expertiseLevel: 'Home cook: name techniques plainly and explain them when needed.',
      recommendedVocabulary: ['ingredients', 'prep', 'bake', 'simmer', 'serve', 'texture', 'flavor'],
      avoidVocabulary: ['health or medical claims', 'invented nutrition values'],
      priorityTopics: ['weeknight dinners', 'baking', 'desserts', 'meal prep', 'seasonal recipes'],
      antiInventionRules: [
        ...COMMON_ANTI_INVENTION,
        'Never invent quantities, cooking times, temperatures, servings or nutrition values that the source does not give.',
        'Never make health, diet or allergy claims unless the source states them.',
      ],
    },
    wordpress: {
      searchIntents: ['recipe / how to make', 'recipe ideas', 'technique', 'substitutions'],
      articleStructures: ['Ingredients → steps → serving and storage for one recipe', 'Recipe idea roundup'],
      seoRules: ['Name the dish and its key descriptor readers search for (e.g. "one-pot pasta", "lemon cake").'],
      detailLevel: 'Precise where the source is precise; otherwise describe the step without inventing figures.',
      faqRules: ['Questions about substitutions, storage, reheating and make-ahead — no invented timings.'],
      linkRules: GENERIC_NICHE_SECTIONS.wordpress.linkRules,
      cta: 'Invite the reader to save the recipe or try it this week.',
    },
    pinterest: {
      angles: ['dish reveal', 'weeknight problem-solution', 'recipe idea list', 'flavor discovery'],
      titleRules: ['Name the dish and what makes it appealing.'],
      descriptionRules: ['Make the dish tempting and say what kind of recipe it is, without the full recipe.'],
      keywordRules: ['Dish + descriptor or occasion (e.g. "chocolate cake recipe", "one-pot dinner ideas").'],
      saveStrategy: 'Pins people save to cook later: one clear dish per pin.',
      diversityRules: ['Vary the dish presentation, the table setting and the angle between pins.'],
      boards: ['Recipes', 'Dinner Ideas', 'Desserts', 'Baking'],
      overlayRules: ['Only when this project uses on-image text.'],
      cta: 'Save this recipe for later.',
    },
    visual: {
      style: 'Culinary food styling: the finished dish in appetizing close detail.',
      framing: 'Overhead or 45-degree.',
      lighting: 'Soft natural light.',
      materials: ['ceramic plates', 'linen napkins', 'wooden boards'],
      colors: ['warm, appetizing tones'],
      props: ['a few key ingredients', 'simple tableware'],
      textInImage: GENERIC_NICHE_SECTIONS.visual.textInImage,
    },
    subNiches: [
      { slug: 'baking', label: 'Baking', aliases: ['Cakes', 'Bread', 'Cookies'], shared: { priorityTopics: ['cakes', 'bread', 'cookies'] } },
      { slug: 'desserts', label: 'Desserts', aliases: ['Dessert', 'Sweets'], shared: { priorityTopics: ['desserts', 'no-bake desserts'] } },
      { slug: 'dinner-ideas', label: 'Dinner Ideas', aliases: ['Dinner', 'Weeknight Dinners', 'Meal Prep'], shared: { priorityTopics: ['weeknight dinners', 'meal prep'] } },
    ],
  },
];
