import {
  FolderOpen,
  Search,
  Sparkle,
  Sparkles,
  ListChecks,
  ImageIcon,
  LayoutGrid,
  LayoutDashboard,
  CalendarClock,
  Download,
  Clock,
  FileText,
  UploadCloud,
} from 'lucide-react';

export interface GuideSection {
  id: string;
  title: string;
  icon: React.ComponentType<{ className?: string }>;
  summary: string;
  points: string[];
}

export const guideSections: GuideSection[] = [
  {
    id: 'command-center',
    title: 'Command Center',
    icon: LayoutDashboard,
    summary: 'The Dashboard is your daily Command Center: what to work on today, which boards are covered, and where your Pin buffer runs short. Every number comes from your own data.',
    points: [
      'The header shows today\'s date, how many priorities you have today, how many projects have an active content stream, and your Credits balance.',
      'Today\'s workspace recommends one focus for today — the content stream that runs out of planned Pins first — with how many days are covered and how many Pins to create or schedule. When every buffer is covered, it tells you so and shows the first date coverage ends.',
      'Today\'s Priorities holds up to 3 priorities and is saved. Add one, rename it, link it to a project, tick it done, or remove it from today (the task is kept). With 3 open priorities, "Replace a priority" asks which one to swap out — nothing is replaced for you.',
      'KPI cards: Tasks Completed (this month), Pins Created, Articles Generated, Projects and Generations are real. Monthly Revenue and Digital Products show "Not tracked yet" until OmniFlow has a source for them.',
      'Recommended next actions ranks what to do next: Create Pins, Schedule Pins (existing Pins without a date come first), Review stream, Review buffer, and the Sunday review. "Add to priorities" lets you edit the title before it is saved — recommendations never change your priorities on their own.',
      'Content streams lists each stream with its board, targets (Pins per day, buffer days), planned Pins, last planned date, days covered, and a status: On track, Needs content, Create now, Warming, Paused, or Needs setup. Missing Pins = Pins per day × buffer days − Pins already planned.',
      'Streams with the Planned status (prepared for later, not started yet) are listed apart under "Planned". They never count as an active project, never raise an urgent alert and are never recommended as today\'s focus. When you start one, edit it and set it to Warming or Active.',
      'Publishing coverage keeps Created, Planned, Planned date passed and Unscheduled Pins apart, and shows a 14-day grid per stream. Dates are the planned dates you set in OmniFlow for the CSV export — OmniFlow cannot see whether Pinterest actually published a Pin.',
      'Published a stream\'s Pins with another tool today? Click today\'s cell in Publishing coverage, enter how many Pins you published (or click "Mark target met" to use the stream\'s Pins per day), add a note if you like, and Save. They count toward today\'s target and show as "Published externally", but never change your Created or Planned counts, your Pins or their dates. Saving again the same day updates the entry. Future days always use the Pins you planned in OmniFlow.',
      'The Sunday analytics review is a weekly routine: start it, go through the checklist (impressions, outbound clicks, saves, compare boards, traffic, then Continue / Scale / Test / Fix / Stop), and mark it complete. If you skip a Sunday it stays Overdue until you complete it.',
      'This week shows Monday to Sunday with Pins planned, Pins to schedule, Pins to create, and tasks due each day. Weekly Progress compares articles published and Pins created this week with your content streams\' targets.',
      'The dashboard only reads and plans. It never generates, schedules or exports Pins by itself.',
    ],
  },
  {
    id: 'projects',
    title: 'Projects & Brand Profile',
    icon: FolderOpen,
    summary: 'Everything you generate belongs to a Project. A Project also holds your Brand Profile, which every generator uses as context.',
    points: [
      'Create a Project before generating any content.',
      'The Brand Profile field (in the Project form) describes your brand, tone, and audience — it is automatically injected into every AI generation for that project. Up to 10,000 characters.',
      'One Project can be marked as default, used to pre-fill the Project selector across the app.',
      'Niche (optional) is a free-text label for the project — pick from suggestions or type your own. For a handful of supported niches (Home Organization & Decor, Personal Finance / Budgeting, Food & Recipes, Travel) it also sets the visual convention AI images follow for that project — framing (full scene vs. close-up object) and, for niches where it fits, whether pin images can include on-image text. Any other niche (or none) keeps the previous conservative default.',
      'Default Language (optional) pre-fills the Language field on the Pinterest and WordPress generation forms when this project is selected — you can always change it before generating.',
      'Click a Project card to open its detail page: Brand Profile, WordPress connection status, quick stats (Pinterest generations, WordPress articles), and shortcuts to that Project\'s Pinterest History, WordPress History, and Categories. The "..." menu on the card still opens Edit/Delete directly, without navigating to the detail page.',
    ],
  },
  {
    id: 'research',
    title: 'Research',
    icon: Search,
    summary: 'Research a topic before generating content — from a keyword, a website, or a blog post.',
    points: [
      'Choose a Source: Keyword (web search), Website URL, or Blog URL.',
      'Results are saved to your Research History for the selected Project.',
      'If a research fails, you\'ll see exactly why (e.g. the site blocked access, or timed out) — use the Retry action on that row to try again.',
      'Research on its own does not change what the AI generates — that happens in the Analyze step.',
    ],
  },
  {
    id: 'analyze',
    title: 'Analyze',
    icon: Sparkle,
    summary: 'Turn raw research into a structured summary the AI can use: theme, audience, tone, category, and keywords.',
    points: [
      'Click "Analyze" on a completed research result to see its structured breakdown.',
      'Re-analyzing the same research result is instant — it reuses the existing analysis instead of calling the AI again.',
      '"Continue to Generate" carries the analysis forward, so your next generation is grounded in real research instead of a bare keyword.',
    ],
  },
  {
    id: 'generate',
    title: 'Generate (Pinterest)',
    icon: Sparkles,
    summary: 'The core feature: turn a keyword into a batch of SEO-optimized Pinterest pins with titles, descriptions, keywords, and image prompts.',
    points: [
      'The form follows your workflow: pick the Project and how many Pins to generate (1 to 30), optionally choose a Board, enter the main Keyword, then choose how the images are created (Generation mode).',
      'Optionally set a Board — leave it blank to let the AI suggest a board per pin.',
      'Right after Board, you can optionally set a Board section — a sub-section inside that board (e.g. "Appetizers" inside "Summer Eats"). It stays empty by default and requires a Board to be set first; the CSV export writes it as "Board/Section" in the same Pinterest board column, never a separate column.',
      'If you arrived from Research → Analyze, you\'ll see a "Using content analysis from Research" indicator confirming that context is active.',
      'Choose a Generation mode. "AI Integrated" (recommended, the default) has the AI create the final image with its headline, subtitle, and call-to-action already designed into it. "Photo Only" gives you a clean photograph with no text. "Legacy Composite" keeps the original workflow where the text and banners are added on top of the photo afterwards.',
      'In AI Integrated mode you can pick a Creative format (Hero Pin, Pattern Guide, Editorial Story, or let the AI choose), a Pinterest strategy (AI recommends, Balanced angles, or a Manual angle), and for the Headline, Subtitle, and CTA either let the AI write them or type the exact text you want (Subtitle and CTA can also be left out). You can also set the maximum number of text lines and how prominent each text is (High, Medium, Low, or None). None means that text element is not generated at all — it is left out of the image and does not use up any text line. At least one of the three must stay enabled, and a text you typed yourself cannot be combined with None.',
      'AI Integrated always writes in the language of your Project — the "Effective language" field shows which one — and the image model is chosen by OmniFlow, not by you.',
      'For Projects whose Niche supports it (e.g. Personal Finance / Budgeting), a "Text in Images" selector appears in Legacy Composite mode: Auto lets the AI decide per pin whether its image should carry a short text overlay or stay a plain photo, Always/Never force one or the other for the whole batch.',
      'In Legacy Composite mode you can optionally upload a Reference Image (JPG/PNG/WebP, 5MB max) to steer the visual style (AI Integrated will support reference images soon — for now the image would not be sent to its image model, so the option is not offered there): the AI analyzes only its color palette, materials, mood, and lighting — never its composition or layout — and applies those as style guidance on top of (not instead of) your Project\'s Niche convention.',
      'In Legacy Composite mode every generated pin image includes a small "Save the Pin!" call-to-action banner near the bottom edge, in the pin\'s own language — this is always on and not configurable per pin. AI Integrated and Photo Only images never get that extra banner.',
      'Titles and descriptions are written to earn the click: each title uses one of five proven angles (curiosity, problem/solution, listicle, discovery, or a direct promise) and varies across the batch, while descriptions build interest without giving away the full answer — so there\'s still a reason to click through.',
    ],
  },
  {
    id: 'editorial',
    title: 'Editorial Review',
    icon: ListChecks,
    summary: 'After generation, review your pins and select exactly which ones to act on before moving further down the pipeline.',
    points: [
      'Use Select All / Select None / Invert to build a selection, or click individual pins.',
      'Actions like Regenerate, Export, and Schedule apply only to your selection — or to everything if nothing is selected.',
      'Click anywhere on a pin card (outside the checkbox and image actions) to open its full details — untruncated title and description, keywords, and the image prompt used for generation, with a Copy button to reuse it elsewhere.',
    ],
  },
  {
    id: 'images',
    title: 'AI Images',
    icon: ImageIcon,
    summary: 'Generate a photorealistic image for each pin from its AI-written image prompt.',
    points: [
      'Generate images for all pins at once, or just your selected pins.',
      'Regenerating a pin\'s image keeps every previous version — open "Versions" on a pin to compare and switch the active one.',
      'Regenerated images are intentionally varied (angle, props, lighting) so you never get the same shot twice.',
    ],
  },
  {
    id: 'boards',
    title: 'Boards',
    icon: LayoutGrid,
    summary: 'Pins are automatically organized into Boards based on the AI\'s suggestion (or the Board you set at generation time).',
    points: [
      'Boards are created automatically the first time their name is used for a Project — no manual setup required.',
      'Open a Board to see every pin generated for it and export just that board\'s pins as CSV.',
      'If some pins have a Board section set, filter chips (All / each section / No section) appear above the pin grid to browse just one section at a time.',
    ],
  },
  {
    id: 'scheduling',
    title: 'Scheduling',
    icon: CalendarClock,
    summary: 'Assign publish dates to your pins so your CSV export is ready to schedule in bulk.',
    points: [
      'Auto-Schedule spreads your pins across days or hours starting from a date and time you choose.',
      'Clear Schedule removes all publish dates in one click if you want to start over.',
    ],
  },
  {
    id: 'export',
    title: 'Export',
    icon: Download,
    summary: 'Every batch of pins can be exported as a CSV file formatted for Pinterest\'s Bulk Upload tool.',
    points: [
      'Export from the Results page, a Board page, or directly from History.',
      'Exports respect your Editorial selection — export just the pins you\'ve selected, or everything.',
    ],
  },
  {
    id: 'history',
    title: 'History',
    icon: Clock,
    summary: 'Every generation you\'ve run lives here, searchable and filterable.',
    points: [
      'Filter by keyword, Project, Board, language, or status.',
      'Results are paginated 20 at a time — use Previous / Next at the bottom of the list.',
      'From here you can revisit results, export CSV, or delete a generation.',
    ],
  },
  {
    id: 'wordpress',
    title: 'WordPress Generator',
    icon: FileText,
    summary: 'Turn a keyword, an external source used as research context, or a set of selected Pinterest pins into a full SEO article: an outline is planned first, then the article is written from it, with a featured image and internal images.',
    points: [
      'The WordPress section opens on a home screen with a few generator cards — today only "1-Click Blog Post" is active, the rest (Bulk Article Generation, Super Page, Rewriter Tool) are coming later.',
      'Enter a keyword, choose a Project and a language — the same Brand Profile used by Pinterest generation is reused here.',
      'Optional Core Settings (Keyword mode only): Article Type (How-to guide, Listicle, Product review, News, Comparison), Article Size (Small/Medium/Large, controlling both length and section count), Tone of Voice, Point of View, and Target Country. All default to "None" — leaving them alone generates exactly as before.',
      'Optional Structure block (Keyword mode only): an Introductory Hook Brief textarea (with 5 one-click presets — Question, Statistical or Fact, Quotation, Anecdotal or Story, Personal or Emotional — still editable after picking one) plus 9 three-state toggles (Conclusion, Tables, H3, Lists, Italics, Quotes, Key Takeaways, FAQ, Bold), each "Non défini" (default) / "Oui" (force it in) / "Non" (force it out). Leaving everything on "Non défini" generates exactly as before.',
      'Optional SEO Keywords block (Keyword mode only): add up to 15 keywords/phrases (type + Enter, or the "Générer avec l\'IA" button for AI-suggested related terms — an honest language-model brainstorm, not a real SERP/NLP tool) that the article is instructed to naturally include at least once each. Empty by default — leaving it untouched generates exactly as before.',
      'Optional External Linking block (Keyword mode only): a comma-separated "Manual URLs" field (up to 10) for specific sources the article should link to. This is additive — every article already gets one automatic, web-search-verified external link regardless of this field. Empty by default — leaving it untouched generates exactly as before.',
      'Or use an external source: switch the Source selector to "External Source", then provide a link to scrape or paste text directly. The source is used only as research context — the topics, angles, and key points it covers, extracted by AI into a short summary — never reproduced or paraphrased closely. The generated article gets its own outline and its own wording. A confirmation checkbox is required before generating.',
      'Or generate from pins: select 1 or more pins on a Pinterest generation page and use "Generate WordPress Article" in the selection toolbar. AI identifies the pins\' common theme and writes one unified article — Project and language are taken from the pins automatically. Fewer than 3 pins still works, with a warning that the result may be thin.',
      'From pins, the featured image is always freshly generated for the article\'s unified theme; internal images reuse every selected pin\'s own already-generated image instead of creating new ones — no fixed cap, select as many pins as the article should draw on.',
      'The article is written only from what you provide (keyword, Brand Profile, research notes, source summary or pins) plus general knowledge: it is instructed never to invent statistics, studies, quotes, prices, dates or results, and never to invent links — only your Manual URLs and the one automatically verified source can appear.',
      'When FAQ is not set to "Non", the generated questions and answers appear in the article itself as a single FAQ section, just before the conclusion.',
      'Generation runs in one request and can take up to a minute (outline, full article, then all images).',
      'Each new article gets an automatic Quality report on its page: a Passed / Warnings / Issues found badge, the problems found (length vs the chosen size, headings, FAQ, links, meta title and description, slug, cut-off text, repetition, language…) and the full list of checks. It is informational only — review it before exporting; it never blocks export or publishing. Articles generated before this feature show "No quality report".',
      'Optionally assign a Category (scoped to the Project) on any of the three flows — this is always a manual choice, never AI-suggested. Pick "+ New Category" in the selector to create one inline, or use the small gear icon next to it to rename or delete existing categories. Leaving it unset files the article under "Uncategorized". WordPress History lets you filter by category and shows a category badge on each article. The category can also be changed afterward, from the article page itself — useful for articles generated before a category existed yet.',
      'The article is stored as Markdown. If the Project has no WordPress connection, use Copy Markdown, Copy HTML, or Download .md to take it anywhere else. If it does, a Publish control replaces those buttons — see "WordPress Publishing" below.',
    ],
  },
  {
    id: 'wordpress-publish',
    title: 'WordPress Publishing',
    icon: UploadCloud,
    summary: 'Connect a Project to a real WordPress site and publish generated articles directly, without leaving OmniFlow.',
    points: [
      'Connect a site from the Project form (Projects → Edit): Site URL, WP Username, and an Application Password — generate one in WordPress under Users → Profile → Application Passwords, it is not your regular login password.',
      'Use "Test Connection" before saving — the credentials are validated against your site before anything is stored. The Application Password is encrypted and never shown again after saving; to change it, use "Change connection" and re-enter it (WordPress credentials are always replaced as a whole, not edited field by field).',
      'One WordPress connection per Project. Disconnecting reverts that project\'s scheduled or published articles back to Draft in OmniFlow — nothing changes on the WordPress site itself.',
      'Once connected, map your OmniFlow categories to real WordPress categories on the WordPress Categories page — matching names are suggested automatically, and you can change any of them. Use "Import from WordPress" to pull your site\'s existing categories in directly instead of creating them by hand first — pick which ones to bring in, and each is created already mapped.',
      'On an article page, use the Publish control: Save as Draft (default), Publish Now, or Schedule (pick a date and time). Featured and internal images are uploaded to your WordPress media library as part of publishing.',
      'A scheduled post is handed to WordPress itself to publish automatically at the chosen time (via WordPress\'s own cron system) — OmniFlow does not need to be open, but the exact timing depends on your site receiving traffic around that time, so it is not always publish-to-the-second.',
      'If a publish attempt fails (e.g. revoked credentials, unreachable site), the exact reason is always shown on the article page — never a silent failure. Republishing after fixing the issue updates the same WordPress post rather than creating a duplicate.',
      'A status badge at the top of every article page — and a compact version on each WordPress History row — always shows whether it has been sent yet: "Not sent to WordPress", "Sent as draft", "Published" (with a direct link to the live post), or "Scheduled for [date]". If you click Publish/Save as Draft/Schedule on an article that was already sent, a confirmation step reminds you when and warns that it will update the existing WordPress post rather than create a duplicate — informational, not a hard block.',
      'Changing an article\'s category from its own page never re-publishes it automatically — if it was already sent to WordPress, the new category only takes effect the next time you publish or update it there.',
    ],
  },
];
