// Static, human-translated "save this pin" CTA variants — never generated by
// the AI. Composited deterministically onto every pin image (see
// compositing.ts) instead of asking the image model to render it, after
// TASK-FIX-018 measured a 1/10 real success rate doing that on flux.2-pro.
// Kept short and simple across all four languages: the previous single fixed
// message (save-pin-message.ts) was long enough to get truncated by the
// image model in some cases, and a fixed-width composited banner has the same
// overflow risk if a variant runs too long — see compositeCtaBanner().
const CTA_MESSAGES: Record<string, string[]> = {
  en: ['Save this Pin', 'Save for later', 'Pin it now', 'Tap to save'],
  de: ['Pin speichern', 'Für später merken', 'Jetzt pinnen', 'Zum Merken tippen'],
  es: ['Guarda este Pin', 'Guarda para después', 'Pinéalo ahora', 'Toca para guardar'],
  fr: ['Enregistre ce Pin', 'À enregistrer plus tard', 'Épingle-le maintenant', 'Appuie pour enregistrer'],
};

// Deterministic rotation across the pins of a batch — same principle as the
// title-angle variation rule (pinterest-pins-v6): `index` is the pin's
// position within the generation batch (see promisePool's callback index in
// app/api/pinterest/generate-images/route.ts), so consecutive pins in the
// same generation don't all show the identical CTA text.
export function pickCtaMessage(language: string, index: number): string {
  const variants = CTA_MESSAGES[language] ?? CTA_MESSAGES.en;
  return variants[index % variants.length];
}
